### ISSUE TITLE
hang up on shutdown

### ISSUE THREAD

**Issue by xaionaro** [xaionaro/openrc-lsb#1]
08:20:34 < zigo> INIT: no more processes left in this runlevel
08:20:40 < zigo> Then that's it, it stays stuck there.
08:20:44 < zigo> Not sure what's going on.
[...]
08:46:57 < heroxbd> xai: if there is no LSB header, lsb2rcconf should output nothing instead of doing some clever guessing
08:52:24 < heroxbd> xai: need some tuning with void lsb_print_orc()

**Comment by xaionaro** [comment]
@heroxbd, can you remind me, is this problem still actual?

**Comment by heroxbd** [comment]
Thanks Demitry!  It is solved by your commit.  We can close this issue now.
